# Generated by Django 4.2.6 on 2023-10-22 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
