# Generated by Django 4.2.6 on 2023-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog_edited_blog_public_id_blog_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
